# Generated by Django 5.1.2 on 2025-02-13 17:52

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_bio_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
