# Generated by Django 5.1.2 on 2024-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='Mytitle', help_text='Enter A Valid Title', max_length=70),
        ),
    ]
