# Generated by Django 5.1.2 on 2024-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(editable=False, max_length=70),
        ),
    ]
