# Generated by Django 5.1.2 on 2025-02-13 18:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_created_alter_article_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
