# Generated by Django 5.1.2 on 2024-11-16 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_author_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 17, 8, 44, 172329, tzinfo=datetime.timezone.utc)),
        ),
    ]
