# Generated by Django 5.1.2 on 2024-11-21 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_category_remove_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.DurationField(default=datetime.timedelta(days=23, seconds=78234)),
        ),
    ]
