# Generated by Django 5.1.2 on 2024-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(null=True),
        ),
    ]
