# Generated by Django 5.1.2 on 2024-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_article_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
