# Generated by Django 5.1.2 on 2024-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_article_myfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('des', models.TextField()),
            ],
        ),
    ]
