# Generated by Django 5.1.2 on 2024-11-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
