# Generated by Django 5.1.2 on 2024-11-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
