# Generated by Django 5.1.2 on 2024-11-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
