# Generated by Django 5.1.2 on 2024-12-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_alter_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
