# Generated by Django 5.1.2 on 2024-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
