# Generated by Django 5.1.2 on 2024-12-09 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_message_created_at_alter_message_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 5, 20, 52, 337036, tzinfo=datetime.timezone.utc)),
        ),
    ]
