# Generated by Django 5.1.2 on 2024-12-10 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0034_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 3, 32, 33, 419248, tzinfo=datetime.timezone.utc)),
        ),
    ]
