# Generated by Django 5.1.2 on 2024-12-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_message_age_alter_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='age',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
