# Generated by Django 5.1.2 on 2024-12-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0036_remove_message_age_remove_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
