# Generated by Django 5.1.2 on 2024-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0037_comment_reading_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reading_time',
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
