# Generated by Django 5.1.2 on 2024-12-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0038_remove_comment_reading_time_article_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
